### ISSUE TITLE
MVVM pattern

### ISSUE THREAD

**Issue by ddthanh198** [ber4444/Android-MVVM-DataBinding-RxJava-Retrofit#1]
I don't think this peoject implement mvvm pattern
Following https://www.vogella.com/tutorials/AndroidArchitecture/article.html,
"The model class contains a data provider and the code to fetch and update the data. The data can be retrieved from different sources, for example:
REST API
Realm db
SQLite db
Handles broadcast
Shared Preferences
Firebase
etc.
Basically the same as the model in the MVP.
"
Why did you put them in ViewModel class?

**Comment by ber4444** [comment]
Yes, it would be abstracted away in a repository.  _Update:_ done.
